# Generated by Django 3.0.2 on 2020-01-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='active',
            field=models.NullBooleanField(),
        ),
    ]
